stages:
  - dev-dockerization

default:
  tags:
    - shared-runner

variables:
  REGISTRY: git.hisoft.com.vn:5050
  GROUP: thanhhung
  IMAGE_NAME: web-admin
  CONTAINER: ${GROUP}-${IMAGE_NAME}
  IMAGE: ${REGISTRY}/${GROUP}/${IMAGE_NAME}
  TAG: latest

dev-dockerization:
  stage: dev-dockerization
  script:
    # Build image
    - docker build -t ${IMAGE}:${TAG} .
    # Push
    - docker login ${REGISTRY} -u ${GITLAB_USER} -p ${GITLAB_PASSWORD}
    - docker push ${IMAGE}:latest
  only:
    refs:
      - deploy-dev

