version: "1.0"
services:
  web:
    image: "git.hisoft.com.vn:5050/thanhhung/web-admin:latest"
    container_name: thanhhung-admin
    build: .
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://thanhhung.tek4.vn
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thanhhung-admin-http.entrypoints=web"
      - "traefik.http.routers.thanhhung-admin-http.rule=Host(`thanhhung-admin.hisoft.com.vn`)"
      - "traefik.http.routers.thanhhung-admin-http.middlewares=https_redirect"
      - "traefik.http.routers.thanhhung-admin.entrypoints=websecure"
      - "traefik.http.routers.thanhhung-admin.rule=Host(`thanhhung-admin.hisoft.com.vn`)"
      - "traefik.http.routers.thanhhung-admin.tls=true"
      - "traefik.http.routers.thanhhung-admin.tls.certresolver=acmeresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    logging:
      driver: "json-file"