export const PREV_RESULT_SIZE = 30
export const NEXT_RESULT_SIZE = 15

export const CHANNEL_SIZE = 20

export enum ACCOUNT_META {
  CUSTOMER = 'CUSTOMER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
}

export enum ACCOUNT_METADATA_KEY {
  ROLES = 'ROLES',
}

export enum CHANNEL_METADATA_KEY {
  ROLES_TYPE = 'ROLES_TYPE',
}

export enum CHANNEL_ROLES_TYPE {
  ADMIN_CUSTOMER = 'ADMIN_CUSTOMER',
  ADMIN_DRIVER = 'ADMIN_DRIVER',
  DRIVER_CUSTOMER = 'DRIVER_CUSTOMER',
  ADMIN_ADMIN = 'ADMIN_ADMIN',
}

export enum SB_GROUP_CUSTOM_TYPE {
  ORDER_GUEST = 'ORDER_GUEST',
  ORDER_DRIVER = 'ORDER_DRIVER',
  SUPPORT_DRIVER = 'SUPPORT_DRIVER',
  SUPPORT_GUEST = 'SUPPORT_GUEST',
  ADMIN_ADMIN = 'ADMIN_ADMIN',
}
